spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library}?useSSL=${POSTGRESQL_SSL:false}&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Ftgyhujikolp112911}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        id:
          new_generator_mappings: false

#  Logging configuration
logging:
  level:
    org.hibernate: INFO
    org.springframework: WARN
    com.university.project: DEBUG